# Generated by Django 5.1.2 on 2024-11-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='token',
            new_name='token_price',
        ),
    ]
