# Generated by Django 5.1.2 on 2024-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_token_token_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_price',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
