# Generated by Django 5.1.3 on 2025-03-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_saleevent_eligible_duration'),
        ('checkout', '0005_invoices_expires_at_invoices_token_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_remaining', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.invoices')),
                ('token_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.token_price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user_data')),
            ],
        ),
    ]
