# Generated by Django 5.1.2 on 2024-11-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_user_data_selected_llm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
