# Generated by Django 5.1.2 on 2024-11-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_user_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
