# Generated by Django 5.1.3 on 2024-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_user_data_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='prompt',
            fields=[
                ('prompt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
