# Generated by Django 5.1.3 on 2025-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_prompt_rename_chats_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='bot_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for the text', max_length=50, unique=True)),
                ('content', models.TextField(help_text='Content of the text to be displayed by the bot')),
                ('description', models.CharField(blank=True, help_text="Description of the text's purpose", max_length=100)),
            ],
        ),
    ]
