# Generated by Django 5.1.3 on 2025-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_bot_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_text',
            name='content',
            field=models.TextField(blank=True, help_text='Content of the text to be displayed by the bot'),
        ),
    ]
