# Generated by Django 5.1.3 on 2025-02-18 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_bot_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='selected_prompt',
            field=models.IntegerField(default=2),
        ),
    ]
