# Generated by Django 5.1.3 on 2025-02-18 16:10

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_user_data_created_at_alter_user_data_selected_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
