# Generated by Django 5.1.3 on 2025-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_saleevent_saleclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
