# Generated by Django 5.1.3 on 2025-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_chat_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleevent',
            name='eligible_duration',
            field=models.DurationField(blank=True, help_text="Only users who registered within this duration from now are eligible. For example, use '90 days' for a 3-month eligibility.", null=True),
        ),
    ]
