# Generated by Django 5.1.2 on 2024-11-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0004_user_data_selected_llm'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('option', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user_data')),
            ],
        ),
    ]
