# Generated by Django 5.1.2 on 2024-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_token_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
