# Generated by Django 5.1.3 on 2025-03-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_invoices_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='token_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.token_price'),
        ),
        migrations.AddField(
            model_name='token_price',
            name='validity_period',
            field=models.IntegerField(default=30, help_text='Validity period in days for these tokens'),
        ),
    ]
