# Generated by Django 5.1.2 on 2024-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='prompt',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='number',
            field=models.IntegerField(),
        ),
    ]
