# Generated by Django 5.1.2 on 2024-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_data_prompt_alter_user_data_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='prompt',
        ),
        migrations.AddField(
            model_name='user_data',
            name='selected_prompt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='token',
            field=models.IntegerField(),
        ),
    ]
