# Generated by Django 5.1.2 on 2024-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_user_data_prompt_user_data_selected_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='selected_llm',
            field=models.CharField(default='gpt-4o', max_length=30),
        ),
    ]
