# Generated by Django 5.1.2 on 2024-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_user_data_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
