# Generated by Django 5.1.3 on 2025-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_prompt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
